### ISSUE TITLE
netdata

### ISSUE THREAD

**Issue by cs-star** [281677160/Lede-OpenWrt#4]
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_PACKAGE_kcptun-client=y
CONFIG_PACKAGE_libnetsnmp=y
CONFIG_PACKAGE_libpci=y
# CONFIG_PACKAGE_luci-app-netdata is not set
CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
# CONFIG_PACKAGE_luci-i18n-netdata-zh-cn is not set
# CONFIG_PACKAGE_netdata is not set
CONFIG_PACKAGE_snmpd=y
CONFIG_PACKAGE_snmpd-static=y
CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_TARGET_ROOTFS_PARTSIZE=300

netdata  日志会一堆err

**Comment by 281677160** [comment]
插件有问题可以去作者那里询问的，如果是原生自带的可以到源码作者那里问问情况，这个问题我看过好像有解决的，在lede的论坛，我没使用这个东西，不过我看到论坛那里有人要所以就带了，我在论坛也跟人说过这个插件没啥用

**Comment by 281677160** [comment]
谢谢提醒，我在.config那里删除了这个了
