### ISSUE TITLE
每次都到这一步有问题，不知道什么原因

### ISSUE THREAD

**Issue by datout** [281677160/Lede-OpenWrt#6]
固件就不全。。编译的k2p
![image](https://user-images.githubusercontent.com/70312079/91931653-a5814f80-ed16-11ea-8c9d-5df3ac8f3a63.png)

**Comment by 281677160** [comment]
固件不全啥意思？固件不全跟这里也没关系，这个也不是错误，说明都没认真看过，等我有空的时候编译一个试试吧

**Comment by 281677160** [comment]
K2P要什么固件的？我编译完成后里面有
openwrt-ramips-mt7621-phicomm_k2p.manifest
openwrt-ramips-mt7621-phicomm_k2p-initramfs-kernel.bin

**Comment by 281677160** [comment]
我知道你说的少了是什么固件了
openwrt-ramips-mt7621-phicomm_k2p-squashfs-sysupgrade.bin  少的是这个吧？
看了下源码，编译固件的时候，固件大小不能超过15MB的，超过这个数，就会没有这个固件

**Comment by 281677160** [comment]
刚测试完了，默认15MB的，只能慢慢挑选插件，基本就是加半个出国软件

我修改了下可以达到30MB的，能顺利的编译出来，但是没机器测试不知道能不能用

还有修改了一下可以达到50MB的，如果你有时间的话，可以测试看看

在diy-lede.sh增加一行代码，第一个是把固件增加到可以达到30MB的，第二个的是可以达到50MB的，你选择一个测试下，或者都编译出来测试下，看看能不能安装，记住，2个代码只能选择一个写入diy-lede.sh，如果不能的话，只能给你做一个不超15MB的diy.config

sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 32448k/g' ./target/linux/ramips/image/mt7621.mk

或者

sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 51200k/g' ./target/linux/ramips/image/mt7621.mk

**Comment by datout** [comment]
> 刚测试完了，默认15MB的，只能慢慢挑选插件，基本就是加半个出国软件
> 
> 我修改了下可以达到30MB的，能顺利的编译出来，但是没机器测试不知道能不能用
> 
> 还有修改了一下可以达到50MB的，如果你有时间的话，可以测试看看
> 
> 在diy-lede.sh增加一行代码，第一个是把固件增加到可以达到30MB的，第二个的是可以达到50MB的，你选择一个测试下，或者都编译出来测试下，看看能不能安装，记住，2个代码只能选择一个写入diy-lede.sh，如果不能的话，只能给你做一个不超15MB的diy.config
> 
> sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 32448k/g' ./target/linux/ramips/image/mt7621.mk
> 
> 或者
> 
> sed -i 's/IMAGE_SIZE := 15744k/IMAGE_SIZE := 51200k/g' ./target/linux/ramips/image/mt7621.mk

确实如此，谢谢大佬解答
